version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ../src:/var/www/html
      - ./log/nginx:/var/log/nginx/
    depends_on:
     - app

  app:
    build:
      ./etc/app
    ports:
      - 6001:6001
    volumes:
      - ../src:/var/www/html
      - ./etc/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: expo
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    command: --innodb_use_native_aio=0

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/bitnami/redis/data
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf
